### ISSUE TITLE
Submitting a crash report 

### ISSUE THREAD

**Issue by vivekkiranpatil** [Norbivar/RTSCamera#5]
[crashreport.txt](https://github.com/Norbivar/RTSCamera/files/11320904/crashreport.txt)

**Comment by Norbivar** [comment]
Well, I can't say for certain. It seems that a base function/code is missing that it's looking for, so it's either : 
- a setup issue -> encountered this before but never been able to figure out what causes it, usually a full clean reinstall helps it
- a version issue

The first option seems more likely, because even if I look at all the releases with version 4.1.23, there is not any change between them that would warrant this error.
